name: Python test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  deploy-wheels:
    name: Tests on ${{ matrix.os }} for ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [36, 37, 38, 39, 310]
        include:
          - os: ubuntu-latest
            python-version: 36
          - os: ubuntu-latest
            python-version: 36
          - os: ubuntu-latest
            python-version: 36
          - os: ubuntu-latest
            python-version: 36
          - os: ubuntu-latest
            python-version: 36
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          echo $(ls -alt)
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest